### ISSUE TITLE
example code

### ISSUE THREAD

**Issue by aliceand** [rm-hull/ssd1306#16]
The original code used as an example in README.md:
   draw.text(30, 40, "Hello World", font=font, fill=255)
caused the following error:
  TypeError: text() got multiple values for keyword argument 'fill'

This change worked for me:
    draw.text((30, 40), "Hello World", font=font, fill=255)

(BTW, thank you for creating the repo.  I'm using it as a base to learn my oled)

**Comment by rm-hull** [comment]
Good spot, thanks.
I've updated the readme accordingly.
Richard
