### ISSUE TITLE
Testing bug fix on SH1106 device

### ISSUE THREAD

**Issue by rm-hull** [rm-hull/ssd1306#2]
Hi @xes,

I pushed some bug fixes and added some more examples (see 08317bc2f261073b57c45b5261a29ede69d202de) - can you run them against your SH1106 device to confirm the changes I made have worked OK?

There was a bug in rendering images (I think i made an assumption pixels were either 255 or 0, but 1-bit images like the pi_logo example are 0 or 1).

Anyway, there's now a `setup.py` which you could try testing against if you dont mind please.

P.s. I guess you'll neeed to edit the example files to reassign the correct device class.

**Comment by xes** [comment]
Hi @rm-hull!
Thank you for the update. I have just checked the setup.py and all the new examples. 
Everything is working perfectly with the sh1106.
Here the photos:
![pi](https://cloud.githubusercontent.com/assets/3456902/6362297/eb5e4538-bc8b-11e4-8839-578aab501d6f.jpg)
![maze](https://cloud.githubusercontent.com/assets/3456902/6362303/f180164e-bc8b-11e4-82cf-111a8ae81e13.jpg)

**Comment by rm-hull** [comment]
Great - thanks !
