### ISSUE TITLE
Skewed text with 128x32 OLED

### ISSUE THREAD

**Issue by thijstriemstra** [rm-hull/ssd1306#23]
I'm testing with a [128x32 OLED](http://www.ebay.com/itm/1PCS-IIC-I2C-0-91-034-128x32-white-OLED-LCD-Display-Module-3-3v-5v-For-Arduino-vv-/272362941188) and when running the sys_info demo for example, the text is unreadable. The logo example shows a stretched logo. Is there possibly an error in the width/height calculation of the ssd1306 device?

**Comment by rm-hull** [comment]
It is possible - maybe quite likely. I have only ever used it on a 128x64 display against the SSD1306 IC, whereupon I got remote help from @xes to get it working on the SH1106 device (see #1).

Is the device you have definitely an SSD1306 ... can you try the SH1106 driver instead (it is in the same module). 

Uploaded photo's would help diagnose the problem further.

**Comment by thijstriemstra** [comment]
I tried SH1106 and it didn't make a difference. It's horrible quality but here's a picture with the sys_info demo (without the 4th wlan line).

![img_20161028_171634613](https://cloud.githubusercontent.com/assets/305679/20043204/12a80cdc-a489-11e6-9df8-6c436adad7dc.jpg)

**Comment by rm-hull** [comment]
It looks as though it is showing every other line of pixels, as if the memory mapping is interleaved.

As an experiment, can you try setting the height to `64`, and run either the *demo.py* or *maze.py* examples - these are full screen and might provide further clues as to what is happening.

**Comment by thijstriemstra** [comment]
@rm-hull I can sponsor and send you one from ebay, if you can email a shipping address to my committers email address.. 👍

**Comment by rm-hull** [comment]
It looks as though the multiplex settings need to be dependent on the height when the class is initialising. See conversation here: http://forum.espruino.com/conversations/269330/

**Comment by rm-hull** [comment]
Related issue: #6

**Comment by rm-hull** [comment]
Have a branch **feature/init_sequence** which _might_ provide the correct initialization sequence for 128x32 and 96x16 sized OLED screens.

@thijstriemstra @eudoxos - could you checkout that branch and run:

    $ sudo python setup.py install
    $ python examples/demo.py --width=128 --height=32

Let me know if that works. 

_Note that some of the other demos will probably assume height=64 - will aim to fix these up as part of the push into master._

**Comment by thijstriemstra** [comment]
Will do. I would recommend `pip install -e .` from the root instead of python setup.py install..

**Comment by thijstriemstra** [comment]
@rm-hull it seems everything is still squashed but only the bottom 50% is visible.

**Comment by rm-hull** [comment]
Pic?

**Comment by thijstriemstra** [comment]
Or it didn't happen..? ;) Let me connect pi camera.

**Comment by rm-hull** [comment]
Actually .... just pushed another commit, if you could pull, install, try again pls?

**Comment by thijstriemstra** [comment]
Ok first the pic; 
![foo](https://cloud.githubusercontent.com/assets/305679/20992240/090c18fe-bce3-11e6-9c35-df1ce1ee4898.jpg)

**Comment by rm-hull** [comment]
Woudl expect to see:
![oled_000001](https://cloud.githubusercontent.com/assets/1915543/20992279/e9d4b098-bcda-11e6-9270-248cc4d85510.png)

**Comment by thijstriemstra** [comment]
But your commit fixed it, nice!! New pic: 
![foo_awb](https://cloud.githubusercontent.com/assets/305679/20992275/41ea922c-bce3-11e6-91f9-b17d777ca512.jpg)

The final part of the demo with the scrolling date/time is not fully visible because of height.

**Comment by rm-hull** [comment]
:+1:

will fix up the sizes for the other demos in the next day or so & push it into master.

**Comment by thijstriemstra** [comment]
The bounce demo goes nuts, not enough space for these balls..

**Comment by eudoxos** [comment]
I tried the init_sequence branch now and I still see random pixels, though with a different pattern. The previous screen (see #70) was and still is with the master branch like this:

![random pixels master branch](https://cloud.githubusercontent.com/assets/1029876/20914680/8a166eee-bb81-11e6-8a39-cf88cd45ff29.jpg)

Now it is like this:

![random pixels init-sequence branch](https://cloud.githubusercontent.com/assets/1029876/21007468/4a861eb0-bd3d-11e6-95bd-adb5384e56bd.png)

Sorry for bad news. Any further diagnostics I can try?

**Comment by rm-hull** [comment]
@eudoxos Ok, thanks for the update: lets re-open your original issue, and move the discussion to there instead

**Comment by rm-hull** [comment]
@thijstriemstra:

> I can sponsor and send you one from ebay, if you can email a shipping address to my committers email address.. :+1: (update: on it's way)


Arrived today, and works great ... thankyou 

_[now I should go back and make sure all the demos work on that screen size]_

**Comment by thijstriemstra** [comment]
Nice!
