### ISSUE TITLE
Add support for SSD1331 color OLED devices

### ISSUE THREAD

**Issue by rm-hull** [rm-hull/ssd1306#43]
* https://www.aliexpress.com/item/Free-Shipping-0-95-inch-7pin-Full-Color-65K-Color-ssd1331-OLED-Display-3-3v-5v/32646204260.html
* http://www.waveshare.com/w/upload/c/c7/SSD1331.pdf

**Comment by thijstriemstra** [comment]
Are these always SPI?

**Comment by rm-hull** [comment]
Yes I think so, ... got one on order.
