### ISSUE TITLE
Add viewport functionality

### ISSUE THREAD

**Issue by rm-hull** [rm-hull/ssd1306#50]
_[thinking out loud]_

Currently the display device only allows for a drawable canvas which is exactly the same size (in pixels) as the physical device.

Add a `viewport` device which is composed of a virtual canvas that can be sized arbitrarily, and a physical device. It should adhere to the same interface as `ssd1306`, but additionally have a method/attribute called `position` that takes an (x,y) tuple. When `viewport.display()` is invoked (either with `with canvas(virtual) as draw` or directly) it updates its underlying virtual image storage, but invokes the physical device to display a portion of the virtual image at the position offset to cover the full size of the phyiscal display.

Likewise when `viewport.position = (x,y)` is invoked, it should re-trigger a refresh on the physical device at the new position offset.

## Example

```python
from oled.device import viewport, ssd1306

virtual = viewport(ssd1306(...), width=1024, height=768)

# initial position is 0,0 - draw text & flush immediately - should show 'hello world'
with canvas(virtual) as draw:
    draw.rectangle((0, 0, 127, 63), outline="white")
    draw.text((10, 10), text="hello world", fill="white")
    draw.text((138, 10), text="the end", fill="white")

# update the viewport one position to the right, causing a refresh, 
# giving a scroll effect to the left
for x in range(128):
    virtual.position = (x, 0)
    time.sleep(0.05) 

# at this point 'the end' will've scrolled into view, and after 2 seconds, 
# underneath that, 'thank you'
time.sleep(2)
with canvas(virtual) as draw:
    draw.text((138, 40), text="Thank you", fill="white")
```

## Considerations
* what happens if you specify a position outside of the virtual canvas?
* should the virtual canvas wrap round?

**Comment by thijstriemstra** [comment]
maybe throw an error if you go outside the canvas unless `wrap=True`?
