### ISSUE TITLE
History management

### ISSUE THREAD

**Issue by thijstriemstra** [rm-hull/ssd1306#73]
Let's say I have a message, an IP address, displayed and an error occurs that needs to be displayed for a few seconds, and then it should revert back to the IP address display. I've implemented something hacky myself but we might as well add something to this library. Thoughts?

**Comment by rm-hull** [comment]
Yeap, sounds like a good idea.
Something like: 

```python
with canvas(device) as draw:
    draw.text((20, 10), text=myip_addr, fill="white")

...

# An error occurs... make a savepoint which is restored later
device.save()

# Now show the error
with canvas(device) as draw:
    draw.text((20, 10), text="Something bad happened", fill="white")
time.sleep(2)

# Restore the previously saved image, and it auto displays
device.restore()
```

The `save`/`restore` methods would just be a stack, so you could have multiple savepoints

**Comment by thijstriemstra** [comment]
How would I get deeper in the stack with multiple savepoints?

**Comment by rm-hull** [comment]
```python
with canvas(device) as draw:
    draw.text((20, 10), text="screen1", fill="white")

device.save()
with canvas(device) as draw:
    draw.text((20, 10), text="screen2", fill="white")

device.save()
with canvas(device) as draw:
    draw.text((20, 10), text="screen3", fill="white")

device.save()
with canvas(device) as draw:
    draw.text((20, 10), text="screen4", fill="white")

time.sleep(2)
device.restore()  # shows 'screen3'

time.sleep(2)
device.restore()  # shows 'screen2'

time.sleep(2)
device.restore()  # shows 'screen1'

time.sleep(2)
device.restore()  # stack exhausted - raises an error (preferred) or does nothing

**Comment by thijstriemstra** [comment]
device.restore(-2)?

**Comment by rm-hull** [comment]
Have pushed a branch *feature/savepoints* which does the above - you wrap an existing device with a `history` class and draw with that (it has the same capabilities as a regular device). Not entirely sure 'history' is the right descriptive word for that class, so may change its name if I can think of anything better. It is up to the caller to manage the calls to `history.restore()` (this can be done by checking `len(history) > 0`, else an index error will result.

There is a sample example, called _savepoint.py_ which has two phases - the first drops every other savepoint (bit like your `device.restore(-2)` idea, but the number is >= 0: it is the number of savepoints to drop before restoring). The second phase reuses the same canvas to draw onto, and restore every point.

![oled_anim](https://cloud.githubusercontent.com/assets/1915543/21372819/937b8dfc-c711-11e6-9cb3-4a0b909fd943.gif)

Anyway, see how this works for your code? I'll try and get it into master and a new version before Christmas.
